name: ESDNew2
channels:
  - simpleitk
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - absl-py=0.13.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py39h3811e60_0
  - async-timeout=3.0.1=py_1000
  - attrs=21.2.0=pyhd8ed1ab_0
  - beautifulsoup4=4.10.0=pyha770c72_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - bottleneck=1.3.2=py39hdd57654_1
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h3811e60_1001
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2022.6.15=ha878542_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2022.6.15=py39hf3d152e_0
  - cffi=1.14.6=py39he32792d_0
  - chardet=4.0.0=py39hf3d152e_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py39hf3d152e_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py39hbca0aa6_0
  - cudatoolkit=11.6.0=hecad31d_10
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=hb2f20db_0
  - einops=0.3.0=py_0
  - expat=2.2.10=he6710b0_2
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.6.0=pyhd8ed1ab_0
  - fontconfig=2.13.0=h9420a91_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - fvcore=0.1.5.post20210804=pyhd8ed1ab_0
  - gdown=4.4.0=pyhd8ed1ab_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.56.2=hd408876_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-auth=1.34.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.38.1=py39hff7568b_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=he6710b0_3
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.6.4=py39hf3d152e_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - joblib=0.17.0=py_0
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h780b84a_1
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.4=pyhd8ed1ab_0
  - matplotlib=3.4.3=py39h06a4308_0
  - matplotlib-base=3.4.3=py39hbbc1b5f_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.2=py39h51133e4_0
  - multidict=5.1.0=py39h3811e60_1
  - munkres=1.1.4=py_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numexpr=2.7.3=py39h22e1b3c_1
  - numpy=1.20.3=py39hf144106_0
  - numpy-base=1.20.3=py39h74d4b33_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1o=h166bdaf_0
  - pandas=1.3.1=py39h8c16a72_0
  - pcre=8.44=he6710b0_0
  - portalocker=2.3.0=py39hf3d152e_0
  - protobuf=3.17.2=py39he80948d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39hf3d152e_3
  - python=3.9.6=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.0=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.1=pyhd3eb1b0_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=5.4.1=py39h3811e60_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - scikit-learn=0.24.2=py39ha9443f7_0
  - scipy=1.6.2=py39had2a1c9_1
  - seaborn=0.11.0=py_0
  - setuptools=52.0.0=py39h06a4308_0
  - simpleitk=2.1.1=py39h3fd9d12_0
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sqlite=3.36.0=hc218d9a_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tensorboard=2.6.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py39h3da14fd_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorboardx=2.4=pyhd8ed1ab_0
  - termcolor=1.1.0=py_2
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.12.0=py39_cu116
  - torchvision=0.13.0=py39_cu116
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.62.1=pyhd8ed1ab_0
  - typing-extensions=3.10.0.0=hd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - tzdata=2021a=h52ac0ba_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.6=py_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py39h3811e60_2
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - addict==2.4.0
    - albumentations==1.1.0
    - anndata==0.8.0
    - commonmark==0.9.1
    - cycler==0.10.0
    - decord==0.6.0
    - efficientnet-pytorch==0.6.3
    - grad-cam==1.3.7
    - h5py==3.7.0
    - huggingface-hub==0.5.1
    - imageio==2.13.5
    - imgaug==0.4.0
    - install==1.3.5
    - kiwisolver==1.3.2
    - llvmlite==0.39.0
    - mmaction==0.5.0
    - mmaction2==0.21.0
    - mmcls==0.23.1
    - mmsegmentation==0.26.0
    - model-index==0.1.11
    - munch==2.5.0
    - natsort==8.1.0
    - networkx==2.6.3
    - numba==0.56.0
    - opencv-contrib-python==4.5.3.56
    - opencv-python==4.5.3.56
    - opencv-python-headless==4.5.3.56
    - openmim==0.2.0
    - ordered-set==4.1.0
    - packaging==21.3
    - patsy==0.5.2
    - pillow==6.2.2
    - pip==22.0.4
    - pretrainedmodels==0.7.4
    - prettytable==3.3.0
    - psutil==5.9.0
    - pydicom==2.2.2
    - pygments==2.12.0
    - pynndescent==0.5.7
    - pywavelets==1.2.0
    - qudida==0.0.4
    - regex==2022.3.15
    - rich==12.4.4
    - sacremoses==0.0.49
    - scanpy==1.9.1
    - scikit-image==0.19.1
    - segmentation-models-pytorch==0.3.0.dev0
    - session-info==1.0.0
    - setproctitle==1.2.2
    - shapely==1.8.1.post1
    - statsmodels==0.13.2
    - stdlib-list==0.8.0
    - tensorboard-logger==0.1.0
    - tifffile==2021.11.2
    - timm==0.4.12
    - tokenizers==0.11.6
    - transformers==4.18.0
    - ttach==0.0.3
    - umap-learn==0.5.3
    - warmup-scheduler==0.3.2
    - wcwidth==0.2.5
    - yapf==0.31.0
prefix: /research/dept8/gds/cyzheng21/conda/envs/ESDNew2
